#! /bin/bash

vol=$(amixer set Master toggle | awk -F'[]%[]' '/%/ {if ($5 == "off") { print "MM" } else { print $2 }}' | head -n 1)

echo "<fc=#e3170d>Vol:</fc> $vol" > /home/antonis/.xmobarVolFifo &
